-- MySQL Script generated by MySQL Workbench
-- 09/06/15 18:00:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`datos_academicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`datos_academicos` (
  `ID_ACADEMICO` INT NOT NULL AUTO_INCREMENT,
  `PROFESION` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL,
  `NIV_INSTRUCCION` INT(2) NULL,
  `ID_JEFE` INT NOT NULL,
  PRIMARY KEY (`ID_ACADEMICO`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`datos_contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`datos_contacto` (
  `ID_CONTACTO` INT NOT NULL AUTO_INCREMENT,
  `TLF_CEL` INT(12) NULL,
  `TLF_HAB` INT(12) NULL,
  `TLF_OFI` INT(12) NULL,
  `EMAIL` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL,
  `ID_JEFE` INT NOT NULL,
  PRIMARY KEY (`ID_CONTACTO`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`datos_encuestado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`datos_encuestado` (
  `ID_ENCUESTADO` INT NOT NULL AUTO_INCREMENT,
  `NOMBRES` VARCHAR(45) NULL,
  `CEDULA` INT(9) NULL,
  `ENCUESTADOR` VARCHAR(30) NULL,
  PRIMARY KEY (`ID_ENCUESTADO`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`datos_familiares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`datos_familiares` (
  `ID_FAMILIARES` INT NOT NULL AUTO_INCREMENT,
  `NOMBRES_F` VARCHAR(30) NULL,
  `CEDULA_F` INT(10) NULL,
  `FECHANAC_F` DATE NULL,
  `EDAD_F` INT(3) NULL,
  `ID_JEFE` INT NOT NULL,
  PRIMARY KEY (`ID_FAMILIARES`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`datos_finanzas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`datos_finanzas` (
  `ID_FINANZAS` INT NOT NULL AUTO_INCREMENT,
  `TRABAJA` VARCHAR(5) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL,
  `TIPO_INGRESO` INT(2) NULL,
  `INGRESO_MENSUAL` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL,
  `ID_JEFE` INT NOT NULL,
  PRIMARY KEY (`ID_FINANZAS`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`datos_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`datos_login` (
  `ID_LOGIN` INT(10) NOT NULL AUTO_INCREMENT,
  `USERADMIN` VARCHAR(20) NULL,
  `CEDULA` INT(9) NULL,
  `PASSADMIN` LONGTEXT NULL,
  `ROL_ADMIN` INT(2) NOT NULL,
  PRIMARY KEY (`ID_LOGIN`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`datos_personales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`datos_personales` (
  `ID_DATAPERSONAL` INT NOT NULL AUTO_INCREMENT,
  `CI` INT NULL,
  `NOMBRE` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL,
  `APELLIDO` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL,
  `F_NAC` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL,
  `EDAD` INT(3) NULL,
  PRIMARY KEY (`ID_DATAPERSONAL`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`datos_relacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`datos_relacion` (
  `ID_RELACION` INT NOT NULL AUTO_INCREMENT,
  `EMBARAZO` VARCHAR(5) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL,
  `CNE` VARCHAR(5) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL,
  `SEXO` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL,
  `EDOCIVIL` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL,
  `ID_JEFE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_RELACION`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`datos_salud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`datos_salud` (
  `ID_SALUD` INT NOT NULL AUTO_INCREMENT,
  `DISCAPACIDAD` VARCHAR(2) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL,
  `TIPO_DISCAPACIDAD` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL,
  `PENSIONADO` VARCHAR(2) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL,
  `INSTITUCION` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL,
  `ID_JEFE` INT NOT NULL,
  PRIMARY KEY (`ID_SALUD`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`evento_noticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`evento_noticia` (
  `ID_EVENT_NOTICIA` INT(10) UNSIGNED NOT NULL,
  `RESPONSABLE` VARCHAR(30) NOT NULL,
  `FCHA_EVENT_NOTICIA` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID_EVENT_NOTICIA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`familiar_academico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`familiar_academico` (
  `ID_ACADEMICO_F` INT NOT NULL AUTO_INCREMENT,
  `GRADO_INSTRUCCION_F` INT(2) NULL DEFAULT NULL,
  `PROFESION_F` INT(2) NULL,
  `ID_JEFE` INT NOT NULL,
  PRIMARY KEY (`ID_ACADEMICO_F`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`familiar_finanzas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`familiar_finanzas` (
  `ID_FINANZAS_F` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `INGMENSUAL_F` VARCHAR(20) NULL DEFAULT NULL,
  `ID_JEFE` INT NOT NULL,
  PRIMARY KEY (`ID_FINANZAS_F`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`familiar_relacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`familiar_relacion` (
  `ID_DETALLE_F` INT NOT NULL AUTO_INCREMENT,
  `PARENTESCO_F` INT(2) NULL,
  `CNE_F` VARCHAR(5) NULL,
  `ID_JEFE` INT NOT NULL,
  PRIMARY KEY (`ID_DETALLE_F`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`familiar_salud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`familiar_salud` (
  `ID_SALUD_F` INT NOT NULL AUTO_INCREMENT,
  `EMBARAZO_F` VARCHAR(5) NULL,
  `DISCAPACIDAD_F` VARCHAR(45) NULL,
  `PENSIONADO_F` VARCHAR(5) NULL,
  `ID_JEFE` INT NOT NULL,
  PRIMARY KEY (`ID_SALUD_F`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`noticias_web`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`noticias_web` (
  `ID_NOTICIAS` INT NOT NULL,
  `IMG_NOTICIAUNO` LONGBLOB NULL DEFAULT NULL,
  `TITULO_NOTICIA` VARCHAR(50) NULL,
  `FCHA_NOTICIA` VARCHAR(30) NULL,
  `CATEG_NOTICIA` VARCHAR(30) NULL,
  `DESCRIPC_NOTICIA` VARCHAR(200) NULL DEFAULT NULL,
  `ID_JEFE` INT NOT NULL,
  PRIMARY KEY (`ID_NOTICIAS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`situacion_economica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`situacion_economica` (
  `ID_SITUACION_ECONOMICA` INT NOT NULL AUTO_INCREMENT,
  `DONDE_TRABAJA` VARCHAR(40) NULL,
  `PREGUNTA_UNO` VARCHAR(3) NULL,
  `ING_FAMILIAR` VARCHAR(10) NULL,
  `ID_JEFE` INT NOT NULL,
  PRIMARY KEY (`ID_SITUACION_ECONOMICA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`situacion_vivienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`situacion_vivienda` (
  `ID_SITUACION_VIVIENDA` INT NOT NULL AUTO_INCREMENT,
  `COND_TERRENO` VARCHAR(30) NULL,
  `FORMA_TENENCIA` VARCHAR(30) NULL,
  `OCV` VARCHAR(3) NULL,
  `TERRENO_PROPIO` VARCHAR(3) NULL,
  `SIVIH` VARCHAR(3) NULL,
  `CONSTANCIA_SIVIH` VARCHAR(3) NULL,
  `COTIZA_LPH` VARCHAR(3) NULL,
  `SALUBRIDAD_VIVIENDA` VARCHAR(30) NULL,
  `ID_JEFE` INT NOT NULL,
  PRIMARY KEY (`ID_SITUACION_VIVIENDA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`condiciones_salud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`condiciones_salud` (
  `ID_CONDICIONES_SALUD` INT NOT NULL AUTO_INCREMENT,
  `PERSONA_ENFERMEDAD` VARCHAR(30) NULL,
  `OTRA_ENFERMEDAD` VARCHAR(3) NULL,
  `AYUDA_ENFERMOS` VARCHAR(3) NULL,
  `TIPO_AYUDA` VARCHAR(45) NULL,
  `SITUACION_EXCLUSION` VARCHAR(30) NULL,
  `CANTIDAD_EXCLUSION` INT(2) NULL,
  `ID_JEFE` INT NOT NULL,
  PRIMARY KEY (`ID_CONDICIONES_SALUD`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`situacion_servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`situacion_servicios` (
  `ID_SITUACION_SERVICIOS` INT NOT NULL AUTO_INCREMENT,
  `AGUAS_BLANCAS` VARCHAR(3) NULL,
  `MEDIDOR` VARCHAR(3) NULL,
  `AGUAS_SERVIDAS` VARCHAR(30) NULL,
  `GAS` VARCHAR(30) NULL,
  `SISTEMA_ELECTRICO` VARCHAR(30) NULL,
  `BOMBILLOS_AHORRADORES` VARCHAR(3) NULL,
  `RECOL_BASURA` VARCHAR(30) NULL,
  `TELEFONIA` VARCHAR(30) NULL,
  `TRANSPORTE` VARCHAR(30) NULL,
  `TIPO_INFORMACION` VARCHAR(40) NULL,
  `SERV_COMUNALES` VARCHAR(30) NULL,
  `ID_JEFE` INT NOT NULL,
  PRIMARY KEY (`ID_SITUACION_SERVICIOS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`participacion_comunitaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`participacion_comunitaria` (
  `ID_PARTICIPACION_COMUNITARIA` INT NOT NULL AUTO_INCREMENT,
  `ORG_COMUNITARIA` VARCHAR(3) NULL,
  `DESCRIPCION` VARCHAR(45) NULL,
  `PARTICIPA` VARCHAR(3) NULL,
  `PARTICIPA_FAMILIAR` VARCHAR(3) NULL,
  `MISIONES_COMUNIDAD` VARCHAR(45) NULL,
  `OTRA_MISION` VARCHAR(45) NULL,
  `ID_JEFE` INT NOT NULL,
  PRIMARY KEY (`ID_PARTICIPACION_COMUNITARIA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalles_vivienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalles_vivienda` (
  `ID_DETALLES_VIVIENDA` INT NOT NULL AUTO_INCREMENT,
  `TIPO_VIVIENDA` VARCHAR(30) NULL,
  `HABITACIONES` VARCHAR(30) NULL,
  `NUM_HABITACIONES` INT(3) NULL,
  `TIPO_PAREDES` VARCHAR(30) NULL,
  `TIPO_TECHO` VARCHAR(30) NULL,
  `ENSERES_VIVIENDA` VARCHAR(30) NULL,
  `INSECTOS_ROEDORES` VARCHAR(3) NULL,
  `ANIMALES_DOMESTICOS` INT(2) NULL,
  `ID_JEFE` INT NOT NULL,
  PRIMARY KEY (`ID_DETALLES_VIVIENDA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ayuda_vivienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ayuda_vivienda` (
  `ID_AYUDA_VIVIENDA` INT NOT NULL AUTO_INCREMENT,
  `TIPO_AYUDA` VARCHAR(30) NULL,
  `DESCRIPCION` VARCHAR(45) NULL,
  `ID_JEFE` INT NOT NULL,
  PRIMARY KEY (`ID_AYUDA_VIVIENDA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalle_servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalle_servicios` (
  `ID_DETALLE_SERVICIOS` INT NOT NULL AUTO_INCREMENT,
  `TANQUE` VARCHAR(3) NULL,
  `TANQUE_LITROS` VARCHAR(5) NULL,
  `PIPOTES` VARCHAR(3) NULL,
  `CANT_PIPOTES` VARCHAR(2) NULL,
  `PROVEEDOR_GAS` VARCHAR(30) NULL,
  `CANT_CILINDROS_GAS` VARCHAR(5) NULL,
  `DURACION_GAS` VARCHAR(15) NULL,
  `PRECIO_GAS` VARCHAR(5) NULL,
  `ID_JEFE` INT NOT NULL,
  PRIMARY KEY (`ID_DETALLE_SERVICIOS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalles_serv_electrico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalles_serv_electrico` (
  `ID_SERV_ELECTRICO` INT NOT NULL AUTO_INCREMENT,
  `MEDIDOR` VARCHAR(3) NULL,
  `BOMBILLOS_NECESITA` VARCHAR(3) NULL,
  `ID_JEFE` INT NOT NULL,
  PRIMARY KEY (`ID_SERV_ELECTRICO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`preguntas_part_comunitaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`preguntas_part_comunitaria` (
  `ID_PREG_PARTCOMUNITARIA` INT NOT NULL AUTO_INCREMENT,
  `P_UNO` VARCHAR(45) NULL,
  `P_DOS` VARCHAR(45) NULL,
  `P_TRES` VARCHAR(45) NULL,
  `P_CUATRO` VARCHAR(45) NULL,
  `P_CINCO` VARCHAR(45) NULL,
  `P_SEIS` VARCHAR(45) NULL,
  `P_SIETE` VARCHAR(45) NULL,
  `P_OCHO` VARCHAR(45) NULL,
  `P_NUEVE` VARCHAR(45) NULL,
  `P_DIEZ` VARCHAR(45) NULL,
  `P_ONCE` VARCHAR(45) NULL,
  `P_DOCE` VARCHAR(45) NULL,
  `OTRA_AREA` VARCHAR(45) NULL,
  `ID_JEFE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_PREG_PARTCOMUNITARIA`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
